### ISSUE TITLE
Include date when `PrettyPrinter(printTime: true)`

### ISSUE THREAD

**Issue by andrei-toterman** [SourceHorizon/logger#80]
`PrettyPrinter` only prints the time of a log event, but not the date, and I think it would be very useful to get that information.
Perhaps it could be even more configurable by adding a `printDate` parameter, so things remain backwards compatible.

**Comment by Bungeefan** [comment]
Hi, good idea!

I tried to create a customizable but still backwards-compatible API for a custom `DateTime` format.
Could you please check out the [`date_time_format`](https://github.com/SourceHorizon/logger/tree/date_time_format) branch and let me know if this would fulfill your use-case? (feel free to provide other feedback as well)

You should be able to just add this to your `pubspec.yaml`:
```yaml
dependency_overrides:
  logger:
    git:
      url: https://github.com/SourceHorizon/logger
      ref: date_time_format
```
